version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auction
    volumes:
      - auction_pg_data:/bitnami/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auction
      - TZ=America/Sao_Paulo
    depends_on:
      - postgres

volumes:
  auction_pg_data:
