version: '3.8'

services:
  postgres-db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - auction_pg_data:/bitnami/postgresql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TZ=America/Sao_Paulo
    depends_on:
      - postgres-db
    command: >
      sh -c "npx prisma migrate deploy && node dist/server.js"

volumes:
  auction_pg_data:
