name: Deploy Node.js API to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Build Docker image
      run: |
        sudo docker build -t nodeapp .
    
    - name: Save Docker image
      run: |
        sudo docker save nodeapp | gzip > nodeapp.tar.gz
    
    - name: Copy Docker image to EC2
      run: |
        scp -o StrictHostKeyChecking=no nodeapp.tar.gz ubuntu@3.237.93.95:/home/ubuntu
    
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.237.93.95 '
          if [ $(sudo docker ps -aq -f name=nodeapp | wc -l) -gt 0 ]; then
            sudo docker stop nodeapp &&
            sudo docker rm nodeapp
          fi;
          sudo docker load < nodeapp.tar.gz &&
          sudo docker run -d --name nodeapp -p 3333:3333 -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -e JWT_SECRET="${{ secrets.JWT_SECRET }}" nodeapp
        '
