name: Deploy Node.js API to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install Node.js
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.80.134.104 '
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - &&
          sudo apt-get install -y nodejs
        '

    - name: Copy application to EC2
      run: |
        rsync -avz --exclude node_modules/ --exclude .git/ -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@3.80.134.104:/home/ubuntu/nodeapp/

    - name: Install dependencies and build TypeScript
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.80.134.104 '
          cd /home/ubuntu/nodeapp &&
          npm install &&
          npm run build
        '

    - name: Set environment variables
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.80.134.104 '
          echo "export DATABASE_URL=${{ secrets.DATABASE_URL }}" &&
          echo "export JWT_SECRET=${{ secrets.JWT_SECRET }}"
        '

    - name: Start the application using Node
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.80.134.104 '
          cd /home/ubuntu/nodeapp &&
          nohup node dist/server.js > app.log 2>&1 &
        '
