name: Deploy Node.js API to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install Node.js
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.210.199.156 '
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - &&
          sudo apt-get install -y nodejs
        '

    - name: Copy application to EC2
      run: |
        rsync -avz --exclude node_modules/ --exclude .git/ -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@3.210.199.156:/home/ubuntu/nodeapp/

    - name: Install dependencies and build TypeScript
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.210.199.156 '
          cd /home/ubuntu/nodeapp &&
          npm install &&
          npm install typescript -g &&
          tsc
        '

    - name: Configure environment variables
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.210.199.156 '
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > /home/ubuntu/nodeapp/.env &&
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> /home/ubuntu/nodeapp/.env
        '

    - name: Start the application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.210.199.156 '
          cd /home/ubuntu/nodeapp &&
          pm2 start dist/server.js --name "nodeapp"
        '
