name: Deploy Node.js API to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install Node.js if not already installed
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.239.191.235 '
          if ! command -v node >/dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&
            sudo apt-get install -y nodejs
          fi
        '
    
    - name: Copy application to EC2
      run: |
        rsync -avz --exclude node_modules/ --exclude .git/ -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@3.239.191.235:/home/ubuntu/nodeapp/
    
    - name: Install dependencies and build TypeScript
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.239.191.235 '
          cd /home/ubuntu/nodeapp &&
          npm install &&
          npm run build
        '
    
    - name: Set persistent environment variables
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.239.191.235 '
          echo "export DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ~/.profile &&
          echo "export JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ~/.profile
        '
    
    - name: Start the application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.239.191.235 '
          cd /home/ubuntu/nodeapp &&
          nohup node dist/server.js > app.log 2>&1 &
        '